### ISSUE TITLE
 has_cap was called with an argument that is deprecated warning

### ISSUE THREAD

**Issue by flacoman91** [sectsect/wp-tag-order#1]
Hi,

Thanks for this plugin.
Upon activating the plugin with the WP_DEBUG flag turned on this warning appears in the admin

 has_cap was called with an argument that is deprectated. Use roles and capabilities instead.

I found the solution here:
https://wordpress.stackexchange.com/a/251976/31604

You can fix this by changing the number 8 to 'manage_options' on line 131 of includes/index.php

**Comment by sectsect** [comment]
Thanks for your feedback.

I have resolved the issue.
Please test the new code and confirm.

**Comment by flacoman91** [comment]
thanks for the fast response!
