### ISSUE TITLE
Feature Request: Select Taxonomies to make sortable

### ISSUE THREAD

**Issue by regiside** [sectsect/wp-tag-order#14]
Wow, thank you for this amazing plugin, this is exactly what I was looking for! It seems like this would be a pretty common need for a lot of development situations. I'm surprised it doesn't seem like anyone's put up anything like it on the WP repository.

One nice optimization would be the ability to select which taxonomies you wanted to be sortable, for larger sites with a lot of posts and/or taxonomies this could save tons of bloat in the options table. For my site I'll have thousands of posts and about 6 taxonomies, but only 1 or two need to be sortable. Let me know if that's something you might add in the future. And thanks again! This saved me tons of time trying to develop my own solution.

P.S. Might also be nice to have a tool in there that could clean up the database (delete custom sort orders) for all taxonomies that aren't currently selected. :D

**Comment by sectsect** [comment]
@regiside 

Thanks for your feedback.
I'm so glad my plugin has helped you in your development.

I'm aware that not being taxonomies selectable is one of the missing features in this plugin.
And, Avoiding database bloat is an important issue.
I hope to implement it in the future, but currently I don't have enough time for it.

You can submit a PR.

Thank you.

**Comment by regiside** [comment]
OK, thanks for your quick response. For now I’ve just hardcoded my desired taxonomies into the plug-in. Unfortunately I’m not really at the skill level to develop the front end functionality, but I might have a go at it if I get some free time.
  

  
- Reggie
  
  
  
    
  

  
  
>

**Comment by sectsect** [comment]
@regiside 
If I implement it, I'll let you know.

**Comment by sectsect** [comment]
@regiside 

I’m sorry to have kept you waiting.

Released in [v2.0.0](https://github.com/sectsect/wp-tag-order/releases/tag/v2.0.0)!
try it.

**Comment by regiside** [comment]
Bro, just came back and checked it out, looks amazing! Thanks so much for all your hard work on this plugin. It's so helpful!

**Comment by sectsect** [comment]
@regiside 
Your feedback helped make this plugin even better.
Thank you.
