### ISSUE TITLE
Order list is empty until taxonomy is clicked.

### ISSUE THREAD

**Issue by regiside** [sectsect/wp-tag-order#15]
A lot of my posts already have taxonomies assigned, when I go to edit the post The taxonomy order list is empty, and I have to add another taxonomy item to get the order list to fill in. Do you know if there’s a line of code I could add to make the taxonomy order fill-in automatically on page load, like it does when I click on a new taxonomy? (This is for posts that don’t have the taxonomy order in the database yet.) No pressure, just figured I’d ask. :)

- Reggie

**Comment by sectsect** [comment]
@regiside 

You can apply to all existing posts with Batch Process on setting page. (Sorry if the recognition is wrong.)
⚠️ Please be sure to backup your database before running.

> - To apply for the existing post, "Add and Remove" once something one tag.
>   Or, if you want to batch apply, Go to Settings -> WP Tag Order page, and click the Apply button.

**Comment by sectsect** [comment]
This issue has been marked as resolved and closed.
Thank you.
