### ISSUE TITLE
Undefined index: post in  wp-content/plugins/wp-tag-order/includes/index.php line 121

### ISSUE THREAD

**Issue by flacoman91** [sectsect/wp-tag-order#2]
on creating new post, this Notice is shown in the admin with debugging turned on.

the $_GET variable should be checked if it exists or a default should be assigned.

**Comment by sectsect** [comment]
Thanks for the feedback.

I think the issue is also fixed.
Please confirm.

**Comment by flacoman91** [comment]
thanks!
