### ISSUE TITLE
Tag order for hierarchical taxonomy

### ISSUE THREAD

**Issue by FabienArr** [sectsect/wp-tag-order#29]
Hello,

What a nice plug-in !
After many weeks, i found your plug-in, i tried and it's what i need.
But, do you think it could be possible to apply that to a hierarchical taxonomy ?

Regards

**Comment by sectsect** [comment]
@FabienArr 
Thanks for your feedback.

Unfortunately I don't think it's possible because the order terms in **hierarchical taxonomy** have a different structure.

**Comment by FabienArr** [comment]
Thank you for your fast reply.
I don't explore yet your sources, but what i analyse in the database, it's that there is no difference in wordpress storage between hierarchical and non-hierarchical taxonomy.

![image](https://user-images.githubusercontent.com/87081538/223727049-59f5b125-68b6-4748-b5ea-f2b8f4214c07.png)

The only difference, it's in the metabox to choose the taxonomy which are checkboxes and not input.

**Comment by sectsect** [comment]
@FabienArr 
What makes this difficult is the different HTML structure between hierarchical and non-hierarchical taxonomy in Meta Box of the edit page, not the database structure.

**Comment by FabienArr** [comment]
It's about your Meta Box or Wordpress Meta box ?

**Comment by sectsect** [comment]
@FabienArr 
It's about WordPress Meta Box.

**Comment by FabienArr** [comment]
Ok, you launch your script on "Add" button but with hierarhical there is no button "Add" so it needs to track each checkbox, it's that ?

**Comment by sectsect** [comment]
@FabienArr 
that's right.
There are structural differences.
This plugin specializes in `non-hierarchical taxonomy`. If we need `hierarchical taxonomy` support, I think it should be developed as a separate plugin.

**Comment by sectsect** [comment]
@FabienArr 
> And after you do a request to get the terms of the taxonomy ?

Submit request after detect changes in taxonomy list.

Since this plugin is not supposed to support hierarchical taxonomy in the first place, I'll have to check that.
Sorry, but I don't have enough time to test to answer this right now.

**Comment by FabienArr** [comment]
@sectsect 
Thanks for your reply, i will try to work on it, it could be interesting to add this feature in your plug-in.
For me the only problem is what i describe, values of checboxes are not store directly via ajax request, but on submit button which reload the page, it's a constraint but at reloading we can have all the terms and we could order them.

**Comment by sectsect** [comment]
@FabienArr 
Thanks for your feature request.
There are some issues such as how to handle nested terms (whether to maintain the hierarchical structure and enable sorting), etc., but I think it would be great if it could be implemented.

I will consider the implementation, including whether it can be implemented.

**Comment by FabienArr** [comment]
@sectsect 
If think it's not the goal to maintain the hierarchical order structure because Wordpress doesn't keep it.
Thanks for considering the request, i can help you, if you want.

**Comment by sectsect** [comment]
@FabienArr 

Hello,

Thank you for your kind words and for taking the time to share your suggestion with us. We're glad to hear that the plugin has been helpful to you!

Regarding your request to apply this functionality to a hierarchical taxonomy, we've carefully reviewed it and, unfortunately, we have decided not to implement this feature at this time. While we understand its potential value, it falls outside the current scope and objectives of this plugin.

We truly appreciate your input, as it helps us better understand user needs and prioritize features. Please feel free to share any other ideas or feedback you may have!

Thank you for your understanding and contribution! 🙌
