### ISSUE TITLE
get_the_terms_ordered should check if tag(s) and custom order exists

### ISSUE THREAD

**Issue by mattmilan** [sectsect/wp-tag-order#3]
Warning: Invalid argument supplied for foreach() in ./plugins/wp-tag-order/includes/category-template.php on line 36

Caused by: the post has no tags or the custom tag order has not been created

**Comment by sectsect** [comment]
@mattmilan 

Thank you for your feedback.
I solved this issue.

Please check [v1.0.6](https://github.com/sectsect/wp-tag-order/releases/tag/v1.0.6) .

Thanks.
