### ISSUE TITLE
Existing post apply not working on bedrock based WP installations

### ISSUE THREAD

**Issue by timiwahalahti** [sectsect/wp-tag-order#5]
Hi! I just noticed that applying to existing posts does not work on custom WP file structures like Bedrock. It is because in `options/includes/ajax-apply.php` there is `wp-load.php` file required assuming that installation uses normal WP file structure.

**Comment by timiwahalahti** [comment]
Also the same goes to `includes/ajax-update.php`.

**Comment by sectsect** [comment]
Thanks for your feedback.

This seems to need to replace the Ajax method in this plugin.
This will take a while, but I will deal with it.

Thanks.

**Comment by sectsect** [comment]
@timiwahalahti 

I modified the Ajax method in this plugin to the WP built-in Ajax (admin-ajax.php).
This should allow Ajax to work well with special file structures.

Please check [v1.1.0](https://github.com/sectsect/wp-tag-order/releases/tag/v1.1.0) .

Thanks.
