### ISSUE TITLE
WordPress 5.0+

### ISSUE THREAD

**Issue by brianrc** [sectsect/wp-tag-order#6]
Anyway to get this working with the new Gutenberg editor in WordPress 5.0+?

**Comment by sectsect** [comment]
@brianrc 

Due to breaking changes at the architectural level of WordPress 5.0, making it work is so hard.

Currently this plugin is NOT compatible with  compatibility with WordPress 5.0.
As a last resort, use [Classic Editor Plugin](https://wordpress.org/plugins/classic-editor/).
