### ISSUE TITLE
Issue with wp-tag-order Plugin and iThemes Security Proxy Detection

### ISSUE THREAD

**Issue by jiyeonLeeLuda** [sectsect/wp-tag-order#66]
Dear wp-tag-order Development Team,

I hope this message finds you well. I am writing to seek your assistance with an issue I have encountered while using the wp-tag-order plugin on my WordPress site.

**Issue Summary:**
The wp-tag-order plugin is not functioning correctly when I attempt to add tags. The tags are not appearing in the Tag Order interface, nor are they being displayed in the posts. This issue began after I changed a setting in the iThemes Security plugin.

**Details:**

WordPress Version: 6.6.1
wp-tag-order Plugin Version: 1.5.2
iThemes Security Plugin Version: 8.1.4

**Steps to Reproduce:**

1. Installed and activated the wp-tag-order plugin.
2. Installed and activated the iThemes Security plugin.
3. Changed the Proxy Detection setting in iThemes Security from "Automatic (insecure)" to "Security Check Scan (Recommended)".
4. Attempted to add new tags using the wp-tag-order plugin.
5. Observed that the tags are not being added to the Tag Order interface or displayed in posts.

**Troubleshooting Performed:**

- Reverted the Proxy Detection setting to "Automatic (insecure)". The issue was resolved.
Based on the troubleshooting, it appears that the Proxy Detection setting in the iThemes Security plugin is affecting the functionality of the wp-tag-order plugin. Specifically, the change to "Security Check Scan (Recommended)" seems to disrupt the tag addition process.

**Request:**
I would appreciate any guidance or suggestions you may have on how to resolve this issue. Is there a known compatibility issue between wp-tag-order and the iThemes Security plugin's Proxy Detection settings? If so, are there any recommended solutions or workarounds that would allow me to use both plugins without conflict?

Thank you for your time and assistance. I look forward to your response.

Best regards,
Jiyeon Lee

**Comment by jiyeonLeeLuda** [comment]
### wp-tag-order Plugin Not Working on Windows 11

I have encountered an issue with the wp-tag-order plugin where it does not function on Windows 11. The plugin works perfectly on macOS, but fails to add and order tags on Windows 11.

**Issue Description:**

Log into the WordPress admin dashboard on a Windows 11 machine.
Attempt to add new tags using the wp-tag-order plugin.
Tags are not added and do not appear in the Tag Order interface.
The same setup works flawlessly on a macOS environment.


**Troubleshooting Steps Performed:**
Disabled Browser Extensions: Attempted with all extensions disabled.
Cleared Browser Cache and Cookies: Cleared all cache and cookies.

Request:
Could you provide any advice or fixes for this issue? If more information is needed, please let me know.

**Comment by sectsect** [comment]
@jiyeonLeeLuda 

Thanks for your feedback.

## iThemes Security

This may be due to the additional verification by iThemes Security rejecting requests to `/wp-admin/admin-ajax.php`.

I checked and found that `Security Check Scan` is a paid PRO version, so it is difficult to reproduce in my environment, but please check the following article to see if it can help resolve the problem.

https://wordpress.org/support/topic/cant-use-ajax-with-solid-security/

## Windows 11

A bug was found in part of JavaScript due to the use of a deprecated event.

I also confirmed that it was not working as expected in the latest version of Chrome, so I released a fixed version **v3.7.0**.

I'm not sure if this is the direct cause, but could you please confirm it.

Thank you in advance.

**Comment by jiyeonLeeLuda** [comment]
Thank you very much for your prompt response and assistance.

As per your guidance, I will install version 3.7.0 and provide feedback.

For now, I need to maintain WordPress version 6.6.1. Therefore, I will download (backup) the existing version 1.5.2 folder to my local computer before proceeding with the installation of the new version.

I will update you after completing the installation and testing.

Thank you again. @sectsect 

Best regards,
Jiyeon Lee.

**Comment by jiyeonLeeLuda** [comment]
Dear @sectsect ,

I appreciate your response and the assistance you've provided.

I have encountered an issue during the installation of version 3.7.0 of the WP Tag Order plugin due to PHP version requirements. My current server environment runs PHP 7.4.33, and upgrading the PHP version is not immediately feasible due to several constraints:

- Legacy Code: The website I maintain is built on legacy code, and there is no separate development server available. Upgrading the PHP version could potentially introduce significant issues without proper testing.

- Non-PHP Developer: My primary expertise is in JavaScript, and I have limited experience with PHP, making it challenging to handle any issues arising from a PHP version upgrade.

I understand that starting from version 3.x, support for PHP 7.x has been dropped. Given my current situation, would it be possible to receive guidance or a version of the plugin that remains compatible with PHP 7.4? Any assistance or alternative solutions you could provide would be greatly appreciated.

Thank you for your understanding and support.

Best regards,
Jiyeon Lee

**Comment by sectsect** [comment]
@jiyeonLeeLuda 

Thank you for your response.

I understand your situation.
To support PHP 7 environments, I have created a branch [php7](https://github.com/sectsect/wp-tag-order/tree/php7) (`v2.3.0`) that is forked from the previous major version `v2.2.5` and fixes bugs.

Try it out.

I also recommend that you test it well.

Note that v2 will not be maintained any more, so I recommend you migrate to PHP 8.

**Comment by jiyeonLeeLuda** [comment]
Dear @sectsect ,

Thanks to your help, I was able to download the new version that supports PHP 7.x and resolve the issue. 
I sincerely appreciate your assistance.

Moving forward, I plan to update to PHP 8 to use the latest version of the plugin. 
Your support has been invaluable, and I once again extend my deepest gratitude.

Thank you so deeply.

Best regards,
Jiyeon Lee
