### ISSUE TITLE
PHP 8.1 Deprecated: Constant FILTER_SANITIZE_STRING.

### ISSUE THREAD

**Issue by regiside** [sectsect/wp-tag-order#71]
I'm using PHP 8.1 and noticed this warning popping up in my PHP log.
`Deprecated: Constant FILTER_SANITIZE_STRING is deprecated in ...plugins/wp-tag-order/includes/index.php on line 143`

This stack exchange question explains why it's deprecated and possible alternatives. 
https://stackoverflow.com/questions/69207368/constant-filter-sanitize-string-is-deprecated

Obviously not a huge deal right now, but I figured I'd mention it.

**Comment by sectsect** [comment]
@regiside 

Thanks for your feedback.

I fixed the deprecation warning for `FILTER_SANITIZE_STRING`.

Released in [v3.7.2](https://github.com/sectsect/wp-tag-order/releases/tag/v3.7.2).
Try it out.

**Comment by sectsect** [comment]
Hi there,

We’re closing this issue due to a lack of recent activity. If you believe this issue is still relevant or have additional information to share, please feel free to reopen it or create a new issue.

Thank you for your understanding and contribution! 🙌
