### ISSUE TITLE
WP Sheet Editor - Post Types (Premium) update term taxonomy order

### ISSUE THREAD

**Issue by cortosdemetraje** [sectsect/wp-tag-order#81]
Hello again!

I'm not sure if this can be solved with wp tag order, but I'd like to raise an issue I've encountered using the WP Sheet Editor - Post Types (Premium) plugin.

This plugin allows you to add posts from a spreadsheet style interface. For me it is extremely useful, since my website, being a catalog of short films, I find it very easy to add content in batch, saving valuable time.

The problem is that when saving the data added in the spreadsheet, the terms are not saved using wp-tag-order, but in alphabetical order, that is, the one used by wordpress.

Is this something that can be fixed?

Thank you very much for your work
![snap](https://github.com/user-attachments/assets/ec931ce1-4fde-4f93-a0bd-3324de972868)

**Comment by sectsect** [comment]
@cortosdemetraje 
This plugin expects reordering to be done by Drag-and-Drop on edit page or via REST API.
It does not support integration with third-party plugins, including the WP Sheet Editor plugin.
As with new posts, you’ll need to reorder manually after importing.

**Comment by cortosdemetraje** [comment]
I imagined. Thx anyway.

Best regards!

**Comment by sectsect** [comment]
@cortosdemetraje 
Thank you for your understanding and contribution 🙌
